---
kind: pipeline
type: docker
name: default

steps:
  - name: api
    image: plugins/docker
    settings:
      repo: registry.home.devmem.ru/gia/api
      registry: registry.home.devmem.ru
      dockerfile: ./compose/django/Dockerfile-drone
      tags:
        - ${DRONE_COMMIT_SHA:0:8}
        - latest

  - name: postgres
    image: plugins/docker
    settings:
      repo: registry.home.devmem.ru/gia/postgres
      registry: registry.home.devmem.ru
      dockerfile: ./compose/postgres/Dockerfile
      context: ./compose/postgres
      tags:
        - latest

  - name: redis
    image: plugins/docker
    settings:
      repo: registry.home.devmem.ru/gia/redis
      registry: registry.home.devmem.ru
      dockerfile: ./compose/redis/Dockerfile
      context: ./compose/redis
      tags:
        - latest
