---
kind: pipeline
name: testing

services:
  - name: postgres
    image: postgres:12-alpine
    environment:
      POSTGRES_USER: dbuser
      POSTGRES_PASSWORD: dbpass

steps:
  - name: test
    image: registry.home.devmem.ru/python:3.8-alpine
    environment:
      DJANGO_DATABASE_URL: postgres://dbuser:dbpass@postgres:5432/dbuser
      DJANGO_SETTINGS_MODULE: config.settings.local
      PYTHONPATH: ${PYTHONPATH}:/drone/src/gia-api
    commands:
      - apk add --no-cache openssl-dev
      - pip install --no-cache-dir -r gia-api/requirements/testing.txt
      - pytest

---
kind: pipeline
name: default

steps:
  - name: api
    image: plugins/docker
    settings:
      repo: registry.home.devmem.ru/gia/api
      registry: registry.home.devmem.ru
      dockerfile: ./compose/django/Dockerfile-drone
      tags:
        - ${DRONE_COMMIT_SHA:0:8}
        - latest
    when:
      branch:
        - master

  - name: postgres
    image: plugins/docker
    settings:
      repo: registry.home.devmem.ru/gia/postgres
      registry: registry.home.devmem.ru
      dockerfile: ./compose/postgres/Dockerfile
      context: ./compose/postgres
      tags:
        - latest
    when:
      branch:
        - master

  - name: redis
    image: plugins/docker
    settings:
      repo: registry.home.devmem.ru/gia/redis
      registry: registry.home.devmem.ru
      dockerfile: ./compose/redis/Dockerfile
      context: ./compose/redis
      tags:
        - latest
    when:
      branch:
        - master
