version: '2'

# docker-compose -f docker-compose.staging.yml up --build -d
# docker-compose -f docker-compose.staging.yml logs
# docker exec -it gia_django-staging_1 python manage.py migrate
# docker exec -it gia_django-staging_1 python manage.py createsuperuser

# Add datasources in admin panel manually

# docker exec -it gia_django-staging_1 python manage.py shell_plus
# from apps.rcoi.models import RcoiUpdater
# RcoiUpdater().run()
# exit()
# docker-compose restart

volumes:
  postgres_data_staging: {}

services:
  redis-staging:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - ./data/staging/redis:/data

  postgres-staging:
    build: ./compose/postgres
    volumes:
      - postgres_data_staging:/var/lib/postgresql/data
      - ./data/staging/backups:/backups
    env_file: .env.staging

  django-staging:
    build:
      context: .
      dockerfile: ./compose/django/Dockerfile-staging
    user: django
    depends_on:
      - postgres-staging
      - redis-staging
    volumes:
      - .:/app
    command: /gunicorn.sh
    env_file: .env.staging

  nginx-staging:
    build:
      context: .
      dockerfile: ./compose/nginx/Dockerfile-staging
    depends_on:
      - django-staging
    ports:
      - "8080:80"
      - "443:443"
