version: '2'

services:
  redis:
    build:
      context: ./compose/redis
      dockerfile: Dockerfile
    volumes:
      - "./redis/data:/data:z"
    restart: always

  postgres:
    build:
      context: ./compose/postgres
      dockerfile: Dockerfile
    volumes:
      - "./db/data:/var/lib/postgresql/data:z"
      - "./db/backups:/backups:z"
    env_file: .env
    restart: always

  django:
    build:
      context: .
      dockerfile: ./compose/django/Dockerfile
    tmpfs:
      - "/tmp"
    depends_on:
      - postgres
      - redis
    env_file: .env
    restart: always

  nginx:
    build:
      context: ./compose/nginx
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    depends_on:
      - django
    restart: always
