version: '2'

volumes:
  postgres_data: {}
  postgres_backups: {}
  redis_data: {}

services:
  redis:
    build:
      context: .docker/redis
      dockerfile: Dockerfile
    volumes:
      - "redis_data:/data:z"
    restart: always

  postgres:
    build:
      context: .docker/postgres
      dockerfile: Dockerfile
    volumes:
      - "postgres_data:/var/lib/postgresql/data:z"
      - "postgres_backups:/backups:z"
    env_file: .env
    restart: always

  django:
    build:
      context: .
      dockerfile: .docker/django/Dockerfile
      args:
        - BUILD_ENVIRONMENT=production
    command: >
      /start
    tmpfs:
      - "/tmp"
    depends_on:
      - postgres
      - redis
    env_file: .env
    restart: always

  nginx:
    build:
      context: .docker/nginx
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    depends_on:
      - django
    restart: always
