version: '2'

volumes:
  postgres_data_staging: {}

services:
  redis-staging:
    build:
      context: ./compose/redis
      dockerfile: Dockerfile
    ports:
      - "6379:6379"
    volumes:
      - "./gia-api/data/staging/redis:/data"

  postgres-staging:
    build:
      context: ./compose/postgres
      dockerfile: Dockerfile
    volumes:
      - "postgres_data_staging:/var/lib/postgresql/data"
      - "./gia-api/data/staging/backups:/backups"
    env_file: .env.staging

  django-staging:
    build:
      context: .
      dockerfile: ./compose/django/Dockerfile-staging
    volumes:
      - "./gia-api:/app"
    command: /gunicorn.sh
    user: django
    depends_on:
      - postgres-staging
      - redis-staging
    env_file: .env.staging

  nginx-staging:
    build:
      context: ./compose/nginx
      dockerfile: Dockerfile-staging
    ports:
      - "8080:80"
      - "443:443"
    depends_on:
      - django-staging
