version: '2'

volumes:
  postgres_data: {}
  postgres_backup: {}

services:
  redis:
    image: redis:alpine
    restart: always

  postgres:
    build: ./compose/postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - postgres_backup:/backups
    env_file: .env
    restart: always

  django:
    build:
      context: .
      dockerfile: ./compose/django/Dockerfile
    user: django
    depends_on:
      - postgres
      - redis
    command: /gunicorn.sh
    env_file: .env
    restart: always

  nginx:
    build: ./compose/nginx
    depends_on:
      - django
    networks:
      - default
      - proxy-tier
    env_file: .env-nginx
    restart: always

networks:
  proxy-tier:
    external:
      name: nginx-proxy
