version: '2'

volumes:
  postgres_data_local: {}
  postgres_backup_local: {}

services:
  postgres-local:
    build:
      context: ./compose/postgres
      dockerfile: Dockerfile
    ports:
      - "5432:5432"
    volumes:
      - "postgres_data_local:/var/lib/postgresql/data"
      - "postgres_backup_local:/backups"
    env_file: .env.local

  django-local:
    build:
      context: .
      dockerfile: ./compose/django/Dockerfile-local
    ports:
      - "8000:8000"
    volumes:
      - ".:/app"
    command: python /app/gia-api/manage.py runserver_plus 0.0.0.0:8000
    depends_on:
      - postgres-local
    env_file: .env.local
