version: '2'

volumes:
  postgres_data_staging: {}
  postgres_backups_staging: {}
  redis_data_staging: {}

services:
  redis-staging:
    build:
      context: .docker/redis
      dockerfile: Dockerfile
    ports:
      - "6379:6379"
    volumes:
      - "./data/staging/redis:/data:z"
    restart: unless-stopped

  postgres-staging:
    build:
      context: .docker/postgres
      dockerfile: Dockerfile
    volumes:
      - "postgres_data_staging:/var/lib/postgresql/data"
      - "./data/staging/backups:/backups:z"
    env_file: .env.staging
    restart: unless-stopped

  django-staging:
    build:
      context: .
      dockerfile: .docker/django/Dockerfile
      args:
        - BUILD_ENVIRONMENT=staging
    command: >
      sh -c "python /app/gia-api/manage.py collectstatic --noinput
      && gunicorn config.wsgi -w 4 -t 60 -b 0.0.0.0:5000 --chdir=/app"
    volumes:
      - ".:/app:z"
      - "./data/staging/staticfiles:/app/gia-api/data/staging/staticfiles:z"
    tmpfs:
      - "/tmp"
    depends_on:
      - postgres-staging
      - redis-staging
    env_file: .env.staging
    restart: unless-stopped

  nginx-staging:
    build:
      context: .docker/nginx
      dockerfile: Dockerfile-staging
    ports:
      - "8080:80"
      - "443:443"
    depends_on:
      - django-staging
    restart: unless-stopped
