version: '2'

services:
  redis:
    build:
      context: ./compose/redis
      dockerfile: Dockerfile
    volumes:
      - "./data/redis:/data"
    restart: always

  postgres:
    build:
      context: ./compose/postgres
      dockerfile: Dockerfile
    volumes:
      - "./data/postgresql:/var/lib/postgresql/data"
      - "./data/backups:/backups"
    env_file: .env
    restart: always

  django:
    build:
      context: .
      dockerfile: ./compose/django/Dockerfile
    depends_on:
      - postgres
      - redis
    user: django
    command: /gunicorn.sh
    env_file: .env
    restart: always

  nginx:
    build:
      context: ./compose/nginx
      dockerfile: Dockerfile
    environment:
      - VIRTUAL_HOST=gia-api.devmem.ru
      - VIRTUAL_NETWORK=nginx-proxy
      - VIRTUAL_PORT=80
      - LETSENCRYPT_HOST=devmem.ru,www.devmem.ru,battery.devmem.ru,cloud.devmem.ru,gia-api.devmem.ru,gia.devmem.ru,plex.devmem.ru,proxmox.devmem.ru,soft.devmem.ru,auth.devmem.ru,autoconfig.devmem.ru,autodiscover.devmem.ru,cp.devmem.ru,demo.devmem.ru,dev.devmem.ru,docker.devmem.ru,fw.devmem.ru,gate.devmem.ru,git.devmem.ru,login.devmem.ru,mail.devmem.ru,mx1.devmem.ru,nas.devmem.ru,proxy.devmem.ru,registry.devmem.ru,router.devmem.ru,spmini.devmem.ru,spsrv.devmem.ru,ssh.devmem.ru,static.devmem.ru,sync.devmem.ru,test.devmem.ru,vpn.devmem.ru
      - LETSENCRYPT_EMAIL=spirkaa@gmail.com
    networks:
      - default
      - proxy-tier
    depends_on:
      - django
    restart: always

networks:
  proxy-tier:
    external:
      name: nginx-proxy
