[tool.pytest.ini_options]
addopts = "--cov=gia-api --cov-report term-missing:skip-covered"

[tool.coverage.run]
branch = true
# plugins = django_coverage_plugin
omit = [
  "*/config/*",
  "*/migrations/*",
  "*__init__.py",
  "*manage.py",
  "*apps.py",
]

[tool.ruff]
ignore = [
  "E203", # whitespace before ':'
  "E501", # line length violations
]
select = [
  "E", # pycodestyle errors
  "W", # pycodestyle warnings
  "F", # pyflakes
  "B", # flake8-bugbear
  "C4", # flake8-comprehensions
  "I", # isort
  "UP", # pyupgrade
  "FBT", # flake8-boolean-trap
  "PIE", # flake8-pie
  "SIM", # flake8-simplify
  "PT", # flake8-pytest-style
  "RET", # flake8-return
  "PTH", # flake8-use-pathlib
  "S", # flake8-bandit
]
target-version = "py311"

[tool.ruff.per-file-ignores]
"*test*" = ["S101"] # allow assert statements in test cases
"gia-api/config/settings/*" = [
  "F403", # star imports
  "F405", # star imports
]

[tool.ruff.isort]
combine-as-imports = true
known-first-party = ["apps"]
