---
- name: "{{ gia_api_name }} - invalidate cache"
  ansible.builtin.command: >
    docker exec {{ gia_api_name }} python manage.py invalidate all
  listen: app_start

- name: check http status
  ansible.builtin.uri:
    url: https://{{ item }}.devmem.ru
    status_code: 200
  register: result
  until: result.status == 200
  retries: 12
  delay: 5
  listen: app_start
  loop:
    - gia-api
    - gia
