FROM registry.home.devmem.ru/python:3.9-alpine

ENV PYTHONUNBUFFERED=1
ARG CRYPTOGRAPHY_DONT_BUILD_RUST=1

COPY gia-api/requirements /app/requirements

RUN set -eux \
    && pip install --no-cache-dir -U -r /app/requirements/staging.txt

COPY .docker/django/gunicorn.sh /gunicorn.sh
COPY .docker/django/entrypoint.sh /entrypoint.sh

RUN set -eux \
    && addgroup django \
    && adduser -D -G django django \
    && sed -i 's/\r//' /entrypoint.sh \
    && sed -i 's/\r//' /gunicorn.sh \
    && chmod +x /entrypoint.sh \
    && chown django /entrypoint.sh \
    && chmod +x /gunicorn.sh \
    && chown django /gunicorn.sh

WORKDIR /app

ENTRYPOINT ["/entrypoint.sh"]
