#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset

export DJANGO_DATABASE_URL

python <<END
import sys
import time

import psycopg

suggest_unrecoverable_after = 30
start = time.time()

while True:
    try:
        psycopg.connect("${DJANGO_DATABASE_URL}")
        break
    except psycopg.OperationalError as error:
        sys.stderr.write("Waiting for PostgreSQL to become available...\n")

        if time.time() - start > suggest_unrecoverable_after:
            sys.stderr.write("  This is taking longer than expected. The following exception may be indicative of an unrecoverable error: '{}'\n".format(error))

    time.sleep(1)
END

echo >&2 'PostgreSQL is available'

exec "$@"
