# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-29 15:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("rcoi", "0002_auto_20170527_2043"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="exam",
            unique_together=set([("date", "level", "place", "employee", "position")]),
        ),
    ]
