# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-13 10:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rcoi', '0006_auto_20170605_2052'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='date',
            options={'ordering': ['-date']},
        ),
        migrations.AlterModelOptions(
            name='exam',
            options={'ordering': ['date']},
        ),
    ]
