# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-22 22:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("rcoi", "0007_auto_20170613_1047"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="exam", options={"ordering": ["date", "id"]},
        ),
        migrations.AlterUniqueTogether(
            name="exam",
            unique_together=set(
                [("date", "level", "place", "employee", "position", "datafile")]
            ),
        ),
    ]
