FROM jfloff/alpine-python:3.7
LABEL maintainer="Ilya Pavlov <piv@devmem.ru>"

ENV PYTHONUNBUFFERED=1

COPY ./gia-api/requirements /requirements

RUN set -eux \
    && apk add --no-cache \
        libpq \
        libxslt-dev \
        libxml2-dev \
        libffi-dev

RUN set -eux \
    && apk add --no-cache --virtual .build-deps \
        postgresql-dev \
	&& pip install --upgrade pip \
    && pip install --no-cache-dir -U -r /requirements/local.txt \
    && apk del .build-deps \
    && rm -rf /requirements

COPY ./compose/django/entrypoint.sh /entrypoint.sh

RUN set -eux \
    && sed -i 's/\r//' /entrypoint.sh \
    && chmod +x /entrypoint.sh

WORKDIR /app

ENTRYPOINT ["/entrypoint.sh"]
