FROM python:3.5-alpine

ENV PYTHONUNBUFFERED 1

# Requirements have to be pulled and installed here, otherwise caching won't work
COPY ./requirements /requirements

RUN apk add --no-cache libpq \
        libxslt-dev \
        libxml2-dev \
     && apk add --no-cache --virtual .build-deps \
        git \
		build-base \
		python3-dev \
        postgresql-dev \
    && pip install -r /requirements/local.txt \
    && apk del .build-deps

COPY ./compose/django/entrypoint.sh /entrypoint.sh
RUN sed -i 's/\r//' /entrypoint.sh
RUN chmod +x /entrypoint.sh

WORKDIR /app

ENTRYPOINT ["/entrypoint.sh"]
