#FROM jfloff/alpine-python:3.8
FROM registry.home.devmem.ru/python:3.8-alpine

ENV PYTHONUNBUFFERED=1
ARG CRYPTOGRAPHY_DONT_BUILD_RUST=1

COPY ./gia-api/requirements /requirements

#RUN set -eux \
#    && apk add --no-cache \
#        libpq \
#        libxslt-dev \
#        libxml2-dev \
#        libffi-dev

RUN set -eux \
    && apk add --no-cache --virtual .build-deps \
        postgresql-dev \
    && pip install --no-cache-dir -U -r /requirements/local.txt \
    && apk del --no-cache .build-deps \
    && rm -rf /var/cache/apk/* \
    && rm -rf /requirements

COPY ./compose/django/entrypoint.sh /entrypoint.sh

RUN set -eux \
    && sed -i 's/\r//' /entrypoint.sh \
    && chmod +x /entrypoint.sh

WORKDIR /app

ENTRYPOINT ["/entrypoint.sh"]
