FROM registry.home.devmem.ru/python:3.7-alpine

ENV PYTHONUNBUFFERED=1

COPY ./compose/django/rootfs /

COPY ./gia-api/requirements /app/requirements

RUN set -eux \
    && apk add --no-cache --virtual .build-deps \
        postgresql-dev \
    && pip install --no-cache-dir -U -r /app/requirements/production.txt \
    && apk del --no-cache .build-deps \
    && rm -rf /var/cache/apk/*

COPY ./gia-api /app

WORKDIR /app
