#FROM jfloff/alpine-python:3.8
FROM registry.home.devmem.ru/python:3.8-alpine

ENV PYTHONUNBUFFERED=1

COPY ./gia-api/requirements /app/requirements

#RUN set -eux \
#    && apk add --no-cache \
#        libpq \
#        libxslt-dev \
#        libxml2-dev \
#        libffi-dev

RUN set -eux \
    && apk add --no-cache --virtual .build-deps \
        postgresql-dev \
    && pip install --no-cache-dir -U -r /app/requirements/staging.txt \
    && apk del --no-cache .build-deps \
    && rm -rf /var/cache/apk/*

COPY ./compose/django/gunicorn.sh /gunicorn.sh
COPY ./compose/django/entrypoint.sh /entrypoint.sh

RUN set -eux \
    && addgroup django \
    && adduser -D -G django django \
    && sed -i 's/\r//' /entrypoint.sh \
    && sed -i 's/\r//' /gunicorn.sh \
    && chmod +x /entrypoint.sh \
    && chown django /entrypoint.sh \
    && chmod +x /gunicorn.sh \
    && chown django /gunicorn.sh

WORKDIR /app

ENTRYPOINT ["/entrypoint.sh"]
