#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset

postgres_ready() {
  python <<END
import psycopg

try:
    c = psycopg.connect("${DJANGO_DATABASE_URL}")
    c.close()
except psycopg.OperationalError:
    raise SystemExit(1)
raise SystemExit()

END
}

until postgres_ready; do
  echo >&2 "$0: Waiting for PostgreSQL to become available..."
  sleep 1
done

exec "$@"
