#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset


postgres_ready() {
python << END
import psycopg2

try:
    psycopg2.connect("${DJANGO_DATABASE_URL}")
except psycopg2.OperationalError:
    raise SystemExit(1)
raise SystemExit()

END
}

until postgres_ready; do
    >&2 echo "$0: Waiting for PostgreSQL to become available..."
    sleep 1
done


exec "$@"
