#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset

postgres_ready() {
  python <<END
import psycopg

try:
    c = psycopg.connect("${DJANGO_DATABASE_URL}")
    c.close()
except psycopg.OperationalError:
    raise SystemExit(1)
raise SystemExit()

END
}

until postgres_ready; do
  echo >&2 "$0: Waiting for PostgreSQL to become available..."
  sleep 1
done

redis_ready() {
  python <<END
import redis

try:
    client = redis.Redis.from_url("${DJANGO_CACHE_URL}")
    client.ping()
except redis.exceptions.ConnectionError:
    raise SystemExit(1)
raise SystemExit()

END
}

until redis_ready; do
  echo >&2 "$0: Waiting for Redis to become available..."
  sleep 1
done

exec "$@"
