# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-28 07:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('name', models.CharField(db_index=True, max_length=100, verbose_name='ФИО')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
            ],
        ),
        migrations.CreateModel(
            name='ExamDate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('date', models.DateField(db_index=True, unique=True, verbose_name='Дата экзамена')),
            ],
            options={
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='ExamLevel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('level', models.CharField(db_index=True, max_length=3, unique=True, verbose_name='Уровень экзамена')),
            ],
            options={
                'ordering': ['level'],
            },
        ),
        migrations.CreateModel(
            name='Organisation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('name', models.CharField(db_index=True, max_length=200, unique=True, verbose_name='Место работы')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('code', models.CharField(db_index=True, max_length=5, verbose_name='Код ППЭ')),
                ('name', models.CharField(db_index=True, max_length=200, verbose_name='Наименование ППЭ')),
                ('addr', models.CharField(db_index=True, max_length=150, verbose_name='Адрес ППЭ')),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from='code')),
            ],
            options={
                'ordering': ['code', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('name', models.CharField(db_index=True, max_length=100, unique=True, verbose_name='Должность в ППЭ')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Territory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('code', models.CharField(db_index=True, max_length=5, unique=True, verbose_name='Код АТЕ')),
                ('name', models.CharField(db_index=True, max_length=100, verbose_name='Наименование АТЕ')),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from='code')),
            ],
            options={
                'ordering': ['code'],
                'verbose_name_plural': 'Territories',
            },
        ),
        migrations.AddField(
            model_name='place',
            name='ate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rcoi.Territory'),
        ),
        migrations.AddField(
            model_name='exam',
            name='date',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rcoi.ExamDate'),
        ),
        migrations.AddField(
            model_name='exam',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rcoi.Employee'),
        ),
        migrations.AddField(
            model_name='exam',
            name='level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rcoi.ExamLevel'),
        ),
        migrations.AddField(
            model_name='exam',
            name='place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rcoi.Place'),
        ),
        migrations.AddField(
            model_name='employee',
            name='org',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rcoi.Organisation'),
        ),
        migrations.AddField(
            model_name='employee',
            name='position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rcoi.Position'),
        ),
        migrations.AlterUniqueTogether(
            name='place',
            unique_together=set([('code', 'name')]),
        ),
        migrations.AlterUniqueTogether(
            name='exam',
            unique_together=set([('date', 'place', 'employee')]),
        ),
        migrations.AlterUniqueTogether(
            name='employee',
            unique_together=set([('name', 'org', 'position')]),
        ),
    ]
