# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-27 20:43
from __future__ import unicode_literals

import django.db.models.deletion
import django_extensions.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rcoi", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DataFile",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True, verbose_name="modified"
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="Имя файла")),
                ("url", models.URLField(unique=True, verbose_name="Ссылка на файл")),
                (
                    "size",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Content-Length"
                    ),
                ),
                (
                    "last_modified",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Last-Modified"
                    ),
                ),
            ],
            options={"ordering": ["-last_modified"],},
        ),
        migrations.AlterModelOptions(
            name="datasource", options={"ordering": ["-modified"]},
        ),
        migrations.AddField(
            model_name="exam",
            name="datafile",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="exams",
                to="rcoi.DataFile",
            ),
            preserve_default=False,
        ),
    ]
