# Generated by Django 2.2.13 on 2020-07-01 15:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rcoi", "0002_tsvector_20200619_0929"),
    ]

    operations = [
        migrations.AlterField(
            model_name="datafile",
            name="name",
            field=models.CharField(
                max_length=50,
                unique=True,
                verbose_name="Имя файла",
            ),
        ),
    ]
