# Generated by Django 5.2.1 on 2025-05-08 21:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("rcoi", "0003_auto_20200701_1536"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="datafile",
            options={"ordering": ("-last_modified",)},
        ),
        migrations.AlterModelOptions(
            name="datasource",
            options={"ordering": ("-modified",)},
        ),
        migrations.AlterModelOptions(
            name="date",
            options={"ordering": ("-date",)},
        ),
        migrations.AlterModelOptions(
            name="employee",
            options={"ordering": ("name",)},
        ),
        migrations.AlterModelOptions(
            name="exam",
            options={"ordering": ("date", "id")},
        ),
        migrations.AlterModelOptions(
            name="level",
            options={"ordering": ("level",)},
        ),
        migrations.AlterModelOptions(
            name="organisation",
            options={"ordering": ("name",)},
        ),
        migrations.AlterModelOptions(
            name="place",
            options={"ordering": ("name",)},
        ),
        migrations.AlterModelOptions(
            name="position",
            options={"ordering": ("name",)},
        ),
        migrations.AlterModelOptions(
            name="subscription",
            options={"ordering": ("employee",)},
        ),
    ]
