# Generated by Django 2.2.13 on 2020-06-11 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("rcoi", "0009_auto_20180523_1350"),
    ]

    operations = [
        migrations.RemoveField(model_name="place", name="ate",),
        migrations.DeleteModel(name="Territory",),
    ]
